Correctly declare gpgoladding COM interfaces
* src/gpgoladdin.h (IDTExtensibility2, IRibbonExtensibility)
 (IRibbonCallback): Add IUnknown and IDispatch methods. Purify.

--
Not sure why this worked before probably because they
did actually implement the relevant methods.
All methods even from base classes should be declared.
PURE ensures that the vtable is generated correclty
fixing the "related undefined reference to vtable"
link errors.